replicaCount: 1
image:
  repository: docker.io/backstage2026/order-batch
  pullPolicy: IfNotPresent
  tag: "0.0.5"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
springProfile: dev
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
httpRoute:
  enabled: true
  name: order-batch-dev-route
  namespace: order-batch-dev
  parentRefs:
    - name: backstage-gateway
      namespace: gateway-system
  matches:
    - path:
        type: PathPrefix
        value: /order-batch-dev
  filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
  backendRefs:
    - name: order-batch-dev
      port: 80
resources: {}
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
